### PR TITLE
Iupac extension (#83)

### PR DESCRIPTION
**Pull request by Lioscro**
Local merge for #83 
@Maarten-vd-Sande

### CODE REVIEW

**Comment by Lioscro** [comment]
@Maarten-vd-Sande Looks good!

**Comment by Maarten-vd-Sande** [comment]
Great! :+1:

**Comment by Maarten-vd-Sande** [comment]
@Lioscro Would it be possible to release this :innocent: ? We are currently implementing a scRNA-seq workflow which makes use of assemblies with the non-accepted IUPAC codes. Our wet-lab colleagues are having troubles installing a fork, and it would be easiest for us if we can just circumvent all these problems with a new release.

**Comment by Lioscro** [comment]
@Maarten-vd-Sande, We are planning a release in a couple of days, tomorrow the latest.

**Comment by Maarten-vd-Sande** [comment]
Oh that is perfect! Thanks for your reply

**Pull request merged**
