### PR TITLE
Iupac extension

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
I downloaded genome GRCh38 through genomepy:

```
genome url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.26_GRCh38/GCF_000001405.26_GRCh38_genomic.fna.gz
annotation url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.26_GRCh38/GCF_000001405.26_GRCh38_genomic.gff.gz
```

When I run kb ref on this I get the error that R is not in BASEPAIRS.

I updated (and renamed) BASEPAIRS/COMPLEMENT to allow all IUPAC codes. My guess would be that kallisto can just work with this right? I'll make sure to test this.

complement cheatsheet I used:

http://arep.med.harvard.edu/labgc/adnan/projects/Utilities/revcomp.html

### CODE REVIEW

**Comment by Lioscro** [comment]
Hi @Maarten-vd-Sande, I believe kallisto replaces non-ACGUT nucleotide with pseudorandom ones, it should work fine. I'll test this out soon.

**Comment by Maarten-vd-Sande** [comment]
@Lioscro sorry for not coming back on this, I kinda forgot.

Yes this seems to work! :tada: 

 Do I need to turn on/off anything for the checks to run? They run on my repository: https://github.com/Maarten-vd-Sande/kb_python/runs/1220628883 . I think the failed code quality is unrelated to my changes, but I don't mind fixing that as it seems simple enough.

**Comment by Maarten-vd-Sande** [comment]
Friendly reminder @Lioscro :)

**Comment by Lioscro** [comment]
Thanks for the bump. Let's merge this into a local branch so that the automated tests can run. We can merge into `devel` once everything passes.

**Pull request merged**
